Repository pknu-wap/2023_1_WAP_APP_TEAM_MEDI, pull requests merged in 2023-07, with the labels that each got.

#163 #162/update/jsp/lib update
  .editorconfig
  build-logic/gradle.properties
  build.gradle.kts
  core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineApprovalListUseCase.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/DataGoKrNetwork.kt
  detekt-config.yml
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/recyclerview/FavoriteMeidicneMoreAdapter.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: enhancement, 박준성, 안드로이드, fix

#166 #165/refactor/tgyuu/favorite medicine refactoring
  core/common/src/main/java/com/android/mediproject/core/common/bindingadapter/BindingAdapter.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/HeaderForElementsView.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
  feature/comments/src/main/res/layout/fragment_my_comments_list.xml
  feature/etc/src/main/java/com/android/mediproject/feature/etc/EtcFragment.kt
  feature/etc/src/main/res/layout/fragment_etc.xml
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineViewModel.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreViewModel.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/recyclerview/FavoriteMedcineMoreDecoration.kt
  feature/favoritemedicine/src/main/res/layout/fragment_favorite_medicine.xml
  feature/favoritemedicine/src/main/res/layout/fragment_favorite_medicine_more.xml
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageMyCommentAdapter.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
  feature/mypage/src/main/res/layout/fragment_my_page.xml
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#168 #167/refactor/tgyuu/my page more refactoring
  app/src/main/java/com/android/mediproject/MainActivity.kt
  core/common/src/main/java/com/android/mediproject/core/common/values.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
  feature/mypage/src/main/res/layout/fragment_my_page_more_bottom_sheet.xml
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#169 #164/update/jsp/systembarstyler
  app/src/main/java/com/android/mediproject/MainActivity.kt
  app/src/main/java/com/android/mediproject/MainViewModel.kt
  app/src/main/res/values/arrays.xml
  core/common/src/main/java/com/android/mediproject/core/common/di/CommonModule.kt
  core/common/src/main/java/com/android/mediproject/core/common/uiutil/SystemBarColorAnalyzer.kt
  core/common/src/main/java/com/android/mediproject/core/common/uiutil/SystemBarStyler.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/WindowViewModel.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseActivity.kt
  feature/camera/src/main/java/com/android/mediproject/feature/camera/MedicinesDetectorFragment.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
  feature/etc/src/main/java/com/android/mediproject/feature/etc/EtcFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
  feature/home/src/main/java/com/android/mediproject/feature/home/HomeFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
  feature/medicine/src/main/java/com/android/mediproject/feature/medicine/main/MedicineInfoFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/NewsFragment.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/SearchMedicinesFragment.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/result/ai/AiSearchResultFragment.kt
Labels: enhancement, 박준성, 안드로이드, 🔨refactor🔨, fix, ⚒️⚒️ 리뷰 완료 충돌 발생 ⚒️⚒️

#172 #170/refactor/tgyuu/comment etc refactoring
  app/src/main/java/com/android/mediproject/MainActivity.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/commentsofamedicine/MedicineCommentsViewModel.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/recentcommentlist/RecentCommentListFragment.kt
  feature/etc/src/main/java/com/android/mediproject/feature/etc/EtcFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#174 #173/refactor/tgyuu/intro refactoring
  core/common/src/main/java/com/android/mediproject/core/common/uiutil/EditableUtil.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/RegexChecker.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/sign/SignUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/requestparameters/LoginParameter.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/intro/src/main/res/layout/fragment_login.xml
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#175 #171/refactor/jsp/token
  app/src/main/java/com/android/mediproject/MainActivity.kt
  core/common/src/main/java/com/android/mediproject/core/common/adapter/GodBindListAdapter.kt
  core/common/src/main/java/com/android/mediproject/core/common/uiutil/SystemBarColorAnalyzer.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/AesCoder.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/ai/VertexAiRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/ai/VertexAiRepositoryImpl.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/comments/CommentsRepositoryImpl.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/di/RepositoryModule.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/token/TokenRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/token/TokenRepositoryImpl.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/DataStoreModule.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSource.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSourceImpl.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenServer.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetTokenUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/token/CurrentTokens.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/token/NewTokensFromAws.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/token/RequestBehavior.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/token/TokenState.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/android/mediproject/core/network/datasource/ai/VertexAiDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/ai/VertextAiDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/NewTokensFromServer.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/TokenDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/TokenDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/TokenResponseInterceptor.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/GoogleNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/NetworkModule.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenInterceptor.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenRequestInterceptor.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenServer.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenServerImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokensModule.kt
  feature/camera/src/main/java/com/android/mediproject/feature/camera/tflite/CameraHelper.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineViewModel.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
Labels: enhancement, 박준성, 안드로이드, 🔨refactor🔨, fix, ⚒️⚒️ 리뷰 완료 충돌 발생 ⚒️⚒️

#177 #176/refactor/tgyuu/home refactoring
  core/common/src/main/java/com/android/mediproject/core/common/mapper/MedicineInfoMapper.kt
  core/common/src/main/res/values/strings.xml
  feature/home/src/main/java/com/android/mediproject/feature/home/HomeFragment.kt
  feature/home/src/main/java/com/android/mediproject/feature/home/HomeViewModel.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/home/src/main/res/values/strings.xml
  feature/search/src/main/java/com/android/mediproject/feature/search/SearchMedicinesViewModel.kt
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#179 #178/feature/jsp/compress cache
  core/data/src/main/java/com/android/mediproject/core/data/remote/di/RepositoryModule.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/medicineapproval/MedicineApprovalRepositoryImpl.kt
  core/database/build.gradle.kts
  core/database/src/main/java/com/android/mediproject/core/database/RoomDB.kt
  core/database/src/main/java/com/android/mediproject/core/database/RoomModule.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/CacheModule.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/DataCacheDao.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineDetailCacheDao.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineDetailCacheDto.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineImageCacheDao.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineImageCacheDto.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/join/MedicineCacheJoinResult.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/manager/DataCacheManager.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/manager/MedicineDataCacheManager.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/manager/MedicineDataCacheManagerImpl.kt
  core/database/src/main/java/com/android/mediproject/core/database/searchhistory/SearchHistoryDao.kt
  core/database/src/main/java/com/android/mediproject/core/database/searchhistory/SearchHistoryMapper.kt
  core/database/src/main/java/com/android/mediproject/core/database/zip/Zipper.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineDetailsUseCase.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/android/mediproject/core/model/local/navargs/MedicineInfoArgs.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/medicineapproval/MedicineApprovalListResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/medicinedetailinfo/MedicineDetailInfoResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/medicinedetailinfo/cache/MedicineCacheEntity.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/android/mediproject/core/network/ResponseWrapper.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/image/GoogleSearchDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/image/GoogleSearchDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/medicineapproval/MedicineApprovalDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/DataGoKrNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/GoogleSearchNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/NetworkModule.kt
  core/network/src/main/java/com/android/mediproject/core/network/parser/HtmlParser.kt
  feature/camera/build.gradle.kts
  feature/medicine/build.gradle.kts
  feature/medicine/src/main/java/com/android/mediproject/feature/medicine/main/MedicineInfoFragment.kt
  feature/medicine/src/main/java/com/android/mediproject/feature/medicine/main/MedicineInfoViewModel.kt
  feature/medicine/src/main/res/layout/fragment_medicine_info.xml
  feature/search/build.gradle.kts
  feature/search/src/main/java/com/android/mediproject/feature/search/result/manual/ManualSearchResultFragment.kt
  gradle/libs.versions.toml
Labels: enhancement, newfeature, 박준성, 안드로이드, fix, 🌟🌟 머지 해주세요 🌟🌟

#181 #180/refactor/jsp/systembar etc
  app/src/main/java/com/android/mediproject/MainActivity.kt
  core/common/src/main/java/com/android/mediproject/core/common/uiutil/SystemBarColorAnalyzer.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/DelayEditTextWatcher.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/DataCacheDao.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineDetailCacheDao.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineImageCacheDao.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/manager/DataCacheManager.kt
  core/database/src/main/java/com/android/mediproject/core/database/cache/manager/MedicineDataCacheManagerImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineApprovalListUseCase.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/image/GoogleSearchDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/medicineapproval/MedicineApprovalDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/NewTokens.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/TokenDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/TokenResponseInterceptor.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/DataGoKrNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/NetworkModule.kt
  core/network/src/main/java/com/android/mediproject/core/network/parameter/LoginRequestParameter.kt
  core/network/src/main/java/com/android/mediproject/core/network/parser/HtmlParser.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenRequestInterceptor.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenServer.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenServerImpl.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseFragment.kt
  feature/camera/src/main/java/com/android/mediproject/feature/camera/MedicinesDetectorFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
Labels: 버그, enhancement, 박준성, 안드로이드, 🔨refactor🔨, fix, 🌟🌟 머지 해주세요 🌟🌟

#189 #184/refactor/tgyuu/penalties refactoring
  core/common/src/main/java/com/android/mediproject/core/common/mapper/MedicineInfoMapper.kt
  core/common/src/main/res/values/color.xml
  core/common/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/penalties/src/main/java/com/android/mediproject/feature/penalties/recentpenaltylist/RecentPenaltyListFragment.kt
  feature/penalties/src/main/java/com/android/mediproject/feature/penalties/recentpenaltylist/RecentPenaltyListViewModel.kt
  feature/penalties/src/main/res/layout/fragment_recent_penalty_list.xml
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🔥🔥 코드 리뷰 기다리는 중 🔥🔥

#190 #188/refactor/tgyuu/merge news and peanlties
  app/build.gradle.kts
  build-logic/convention/build.gradle.kts
  core/common/build.gradle.kts
  core/data/build.gradle.kts
  core/domain/build.gradle.kts
  core/model/build.gradle.kts
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/android/mediproject/feature/home/HomeFragment.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/medicine/build.gradle.kts
  feature/news/build.gradle.kts
  feature/news/src/main/java/com/android/mediproject/feature/news/NewsFragment.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/penalties/recentpenaltylist/PenaltyListAdapter.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/penalties/recentpenaltylist/RecentPenaltyListFragment.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/penalties/recentpenaltylist/RecentPenaltyListViewModel.kt
  feature/news/src/main/res/layout/fragment_recent_penalty_list.xml
  feature/news/src/main/res/values/colors.xml
  feature/news/src/main/res/values/strings.xml
  feature/penalties/.gitignore
  feature/penalties/build.gradle.kts
  feature/penalties/consumer-rules.pro
  feature/penalties/proguard-rules.pro
  feature/penalties/src/main/AndroidManifest.xml
  feature/penalties/src/main/java/com/android/mediproject/feature/penalties/recentpenaltylist/PenaltyListAdapter.kt
  feature/penalties/src/main/res/values/strings.xml
  feature/penalties/src/test/java/com/android/mediproject/feature/penalties/ExampleUnitTest.kt
  feature/search/build.gradle.kts
  settings.gradle.kts
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟
