Repository pknu-wap/2023_1_WAP_APP_TEAM_MEDI, pull requests merged in 2023-06, with the labels that each got.

#97 #93/feature/tgyuu/my page token logic
  core/common/build.gradle.kts
  core/common/src/main/java/com/android/mediproject/core/common/bindingadapter/BindingAdapter.kt
  core/common/src/main/java/com/android/mediproject/core/common/uiutil/DialogUtil.kt
  core/common/src/main/java/com/android/mediproject/core/common/values.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSource.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSourceImpl.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenServer.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetTokenUseCase.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/sign/GetUserUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/local/navargs/LoginFromMyPageArgs.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenInterceptor.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Subtitle.kt
  core/ui/src/main/res/drawable/rectangle_5_white_main.xml
  core/ui/src/main/res/layout/subtitle.xml
  core/ui/src/main/res/values/string.xml
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterestedMedicineFragment.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterstedMedicineViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
  feature/mypage/src/main/res/layout/fragment_my_page_more_dialog.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/search/src/main/res/layout/fragment_manual_search_result.xml
Labels: enhancement, 안태규, 안드로이드, 디자인, 🔨refactor🔨

#103 #102/fix/juno/recent browsed model bug
  .github/ISSUE_TEMPLATE/issue---feature_request.md
  .github/ISSUE_TEMPLATE/issue---project_settings.md
  .github/ISSUE_TEMPLATE/issue-bug-template.yml
  .github/ISSUE_TEMPLATE/issue-feature-template.yml
  .github/ISSUE_TEMPLATE/issue-project-settings.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.yml
  README.md
  server/bin/www.js
  server/src/models/user.js
Labels: enhancement, 문준호, 백엔드

#104 #68/feature/juno/favorate medicine
  server/src/config/jwt.js
  server/src/config/responseMsg.js
  server/src/controller/medicine/favorite/favorite.ctrl.js
  server/src/routes/medicine/favorite/index.js
  server/src/routes/medicine/index.js
  server/src/routes/user/userRouter.js
  server/src/service/medicineService.js
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드

#106 #105 관심 약 여부 조회 기능 개발
  server/src/controller/medicine/favorite/favorite.ctrl.js
  server/src/routes/medicine/favorite/index.js
  server/src/service/medicineService.js
Labels: enhancement, 문준호, 서재완, 백엔드

#109 #108/fix/juno/fix reissue token
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드, fix

#114 #113/feature/juno/user info management
  server/src/config/responseMsg.js
  server/src/controller/user/user.ctrl.js
  server/src/routes/user/userRouter.js
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드

#118 #117 의약품 ID 반환 API의 HTTP method POST로 변경
  server/src/routes/medicine/comment/index.js
Labels: 버그, 문준호, 백엔드, fix

#125 #124 로그인, 회원가입 API 반환값에 유저 정보 포함
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드

#120 #103/feature/tgyuu/my page interested medicine
  core/common/src/main/java/com/android/mediproject/core/common/values.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/di/RepositoryModule.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/interestedmedicine/InterestedMedicineRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/interestedmedicine/InterestedMedicineRepositoryImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetInterestedMedicineUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/InterestedMedicine/InterestedMedicineDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/InterestedMedicine/InterestedMedicineListResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/InterestedMedicine/MedicineInterestedDto.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/interestedmedicine/InterestedMedicineDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/interestedmedicine/InterestedMedicineDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/interestedmedicine/build.gradle.kts
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterestedMedicineFragment.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterstedMedicineViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
  feature/penalties/src/main/java/com/android/mediproject/feature/penalties/recentpenaltylist/PenaltyListAdapter.kt
  feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingFragment.kt
Labels: enhancement, 안태규, 안드로이드, 🔨refactor🔨

#126 #121/feature/tgyuu/my page more logic
  core/common/src/main/java/com/android/mediproject/core/common/values.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/di/RepositoryModule.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/user/UserRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/user/UserRepositoryImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/sign/GetUserUseCase.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/user/UserUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/requestparameters/ChangeNicknameParameter.kt
  core/model/src/main/java/com/android/mediproject/core/model/requestparameters/ChangePasswordParamter.kt
  core/model/src/main/java/com/android/mediproject/core/model/requestparameters/ChangePasswordRequestParameter.kt
  core/model/src/main/java/com/android/mediproject/core/model/user/remote/ChangeNicknameResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/user/remote/ChangePasswordResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/user/remote/UserResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/user/remote/WithdrawalResponse.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/user/UserDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/user/UserDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenInterceptor.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseFragment.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseViewModel.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Subtitle.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/layout/fragment_my_page_more_dialog.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: enhancement, 안태규, 안드로이드, 🔨refactor🔨

#135 #131/feature/tgyuu/bar top padding
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/moreinterestedmedicine/MoreInterestedMedicineFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
Labels: enhancement, 안태규, 안드로이드

#140 #139/refactor/tgyuu/change nickname,withdrawale ehancement
  core/datastore/src/main/java/com/android/mediproject/core/datastore/AppDataStore.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/AppDataStoreImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/user/UserUseCase.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
Labels: enhancement, 안태규, 안드로이드, 🔨refactor🔨

#141 #139 refact removeTokens() 로직 보완
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSourceImpl.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenServer.kt
Labels: 안태규, 안드로이드, 🔨refactor🔨

#142 1차 메인 빌드
  .DS_Store
  .github/ISSUE_TEMPLATE/issue---feature_request.md
  .github/ISSUE_TEMPLATE/issue---project_settings.md
  .github/ISSUE_TEMPLATE/issue-bug-template.yml
  .github/ISSUE_TEMPLATE/issue-feature-template.yml
  .github/ISSUE_TEMPLATE/issue-project-settings.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.yml
  .idea/.gitignore
  .idea/misc.xml
  .vscode/launch.json
  README.md
  package-lock.json
  server/.DS_Store
  server/README.md
  server/app.js
  server/bin/www.js
  server/package-lock.json
  server/package.json
  server/src/.DS_Store
  server/src/config/jwt.js
  server/src/config/response.js
  server/src/config/responseMsg.js
  server/src/config/sequelize.js
  server/src/controller/comment/index.js
  server/src/controller/medicine/favorite/favorite.ctrl.js
  server/src/controller/user/user.ctrl.js
  server/src/models/comment.js
  server/src/models/favoriteMedicine.js
  server/src/models/like.js
  server/src/models/medicine.js
  server/src/models/test.js
  server/src/models/user.js
  server/src/routes/home/index.js
  server/src/routes/medicine/comment/index.js
  server/src/routes/medicine/favorite/index.js
  server/src/routes/medicine/index.js
  server/src/routes/user/userRouter.js
  server/src/service/commentService.js
  server/src/service/medicineService.js
  server/src/service/userService.js
  server/swagger/swagger.js
Labels: 백엔드

#145 #144/feature/tgyuu/logout
  core/common/src/main/java/com/android/mediproject/core/common/values.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetInterestedMedicineUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/interestedmedicine/InterestedMedicineDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/interestedmedicine/InterestedMedicineListResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/interestedmedicine/MoreInterestedMedicineDto.kt
  core/network/build.gradle.kts
  feature/interestedmedicine/build.gradle.kts
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/moreinterestedmedicine/MoreInterestedMedicineFragment.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/moreinterestedmedicine/MoreInterestedMedicineViewModel.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/moreinterestedmedicine/MoreInterestedMeidicneAdapter.kt
  feature/interestedmedicine/src/main/res/layout/item_interested_medicine.xml
  feature/intro/build.gradle.kts
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
  feature/mypage/src/main/res/layout/fragment_my_page_more_bottom_sheet.xml
  feature/mypage/src/main/res/layout/fragment_my_page_more_dialog.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: enhancement, 안태규, 안드로이드, 디자인, 🔨refactor🔨

#153 #91 사용되지 않는 로직 정리
  .idea/misc.xml
  app/src/main/java/com/android/mediproject/MainActivity.kt
  app/src/main/java/com/android/mediproject/MediApplication.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/UriBuilder.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/granule/GranuleIdentificationRepositoryImpl.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSourceImpl.kt
  core/model/src/main/java/com/android/mediproject/core/model/DataGoKrBaseResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/awscommon/BaseAwsQueryResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/awscommon/BaseAwsSignResponse.kt
  core/network/src/main/java/com/android/mediproject/core/network/InternetNetworkListener.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/comments/CommentsListDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/penalties/recallsuspension/RecallSuspensionListDataSourceImpl.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/HeaderForElementsView.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/MediSearchbar.kt
  feature/camera/src/main/java/com/android/mediproject/feature/camera/confirmdialog/ConfirmDialogFragment.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/commentsofamedicine/MedicineCommentsViewModel.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListViewModel.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/recentcommentlist/RecentCommentListViewModel.kt
  feature/home/src/main/java/com/android/mediproject/feature/home/HomeViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/NewsViewModel.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/AdminActionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsuspension/RecallSuspensionScreen.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/recentsearchlist/RecentSearchListFragment.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/result/ai/AiSearchResultViewModel.kt
  feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingFragment.kt
Labels: enhancement, 박준성, 안드로이드, fix

#154 #152 add 개발버전 워터마크 추가
  app/src/main/res/layout/activity_main.xml
Labels: enhancement, 안태규, 안드로이드
