Repository pknu-wap/2023_1_WAP_APP_TEAM_MEDI, pull requests merged in 2023-05, with the labels that each got.

#19 #11/feature/tgyuu/login
  build.gradle.kts
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/IntroButton.kt
  core/ui/src/main/res/drawable/rectangle_5.xml
  core/ui/src/main/res/drawable/rectangle_5_white.xml
  core/ui/src/main/res/layout/introbutton.xml
  core/ui/src/main/res/layout/subtitle.xml
  core/ui/src/main/res/values/attrs.xml
  core/ui/src/main/res/values/color.xml
  core/ui/src/main/res/values/dimens.xml
  feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/res/drawable/signup.xml
  feature/intro/src/main/res/layout/fragment_intro.xml
  feature/intro/src/main/res/layout/fragment_login.xml
  feature/intro/src/main/res/layout/fragment_sign_up.xml
  feature/intro/src/main/res/navigation/intro_nav.xml
  feature/intro/src/main/res/values/colors.xml
  feature/intro/src/main/res/values/dimens.xml
  feature/intro/src/main/res/values/strings.xml
Labels: 설계, newfeature, 안태규, 안드로이드

#23 #12/feature/tgyuu/my page
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/HeaderForElementsView.kt
  core/ui/src/main/res/values/color.xml
  core/ui/src/main/res/values/string.xml
  feature/home/src/main/res/layout/fragment_home.xml
  feature/interestedmedicine/build.gradle.kts
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterestedMedicineFragment.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterstedMedicineViewModel.kt
  feature/interestedmedicine/src/main/res/layout/fragment_interested_medicine.xml
  feature/interestedmedicine/src/main/res/values/strings.xml
  feature/intro/src/main/res/layout/fragment_login.xml
  feature/intro/src/main/res/layout/fragment_sign_up.xml
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/res/drawable/default_user_image.xml
  feature/mypage/src/main/res/drawable/dot_3_vertical.xml
  feature/mypage/src/main/res/drawable/rectangle_5_main.xml
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 설계, 안태규, 안드로이드

#27 #25/feature/tgyuu/setting
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Bar.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/SettingBar.kt
  core/ui/src/main/res/drawable/right_arrow.xml
  core/ui/src/main/res/layout/bar.xml
  core/ui/src/main/res/layout/settingbar.xml
  core/ui/src/main/res/values/attrs.xml
  feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroViewModel.kt
  feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingFragment.kt
  feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingViewModel.kt
  feature/setting/src/main/res/layout/fragment_setting.xml
  feature/setting/src/main/res/values/string.xml
  feature/setting/src/main/res/values/strings.xml
Labels: 설계, enhancement, 안태규, 안드로이드

#29 #28/feat/intro모듈 navigation Action flow 및 모든 Fragment handleEvent 함수 private으로 변경
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Subtitle.kt
  core/ui/src/main/res/values/attrs.xml
  feature/community/src/main/java/com/android/mediproject/feature/community/CommunityFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/intro/src/main/res/layout/fragment_login.xml
  feature/intro/src/main/res/layout/fragment_sign_up.xml
  feature/intro/src/main/res/navigation/intro_nav.xml
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingFragment.kt
Labels: 설계, enhancement, 안태규, 안드로이드

#38 #37/feature/juno/jwt
  package-lock.json
  server/README.md
  server/bin/www.js
  server/package-lock.json
  server/package.json
  server/src/config/jwt.js
  server/src/config/sequelize.js
  server/src/controller/user/user.ctrl.js
  server/src/models/test.js
  server/src/models/user.js
  server/src/routes/home/index.js
  server/src/routes/user/userRouter.js
Labels: enhancement, 문준호, 서재완, 백엔드

#39 #22/feature/juno/sign up
  server/app.js
  server/package-lock.json
  server/package.json
  server/src/config/jwt.js
  server/src/config/responseMsg.js
  server/src/controller/user/user.ctrl.js
  server/src/models/user.js
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드

#41 #21/feature/juno/sign in
  server/src/config/jwt.js
  server/src/config/response.js
  server/src/config/responseMsg.js
  server/src/controller/user/user.ctrl.js
  server/src/models/user.js
  server/src/routes/user/userRouter.js
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드

#45 #43/feature/juno/reissue token
  server/src/config/jwt.js
  server/src/config/responseMsg.js
  server/src/controller/user/user.ctrl.js
  server/src/routes/user/userRouter.js
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드

#47 #20 Sequelize model, hook 정의 및 테스트
  server/bin/www.js
  server/src/models/comment.js
  server/src/models/favoriteMedicine.js
  server/src/models/like.js
  server/src/models/medicine.js
  server/src/models/recentBrowsed.js
  server/src/models/test.js
  server/src/models/user.js
Labels: enhancement, 문준호, 서재완, 백엔드

#49 #24/feature/tgyuu/my commnets list
  .idea/.gitignore
  .idea/compiler.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/navigation/main_nav.xml
  core/model/src/main/java/com/android/mediproject/core/model/comments/MyCommentDto.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/commentsofamedicine/CommentsAdapter.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListAdapter.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListDecoration.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListViewModel.kt
  feature/comments/src/main/res/drawable/comment.xml
  feature/comments/src/main/res/layout/fragment_medicine_comments.xml
  feature/comments/src/main/res/layout/fragment_my_commnets_list.xml
  feature/comments/src/main/res/layout/fragment_recent_comment_list.xml
  feature/comments/src/main/res/layout/item_my_commnet.xml
  feature/comments/src/main/res/navigation/comments_nav.xml
  feature/comments/src/main/res/values/dimens.xml
  feature/comments/src/main/res/values/strings.xml
  feature/community/src/main/res/navigation/community_nav.xml
  feature/intro/src/main/res/navigation/intro_nav.xml
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/news/src/main/res/layout/fragment_news.xml
  feature/news/src/main/res/navigation/news_nav.xml
Labels: 설계, 안태규, 안드로이드

#53 #52/bugs/fixed glides
  app/build.gradle.kts
  app/src/main/java/com/android/mediproject/MainActivity.kt
  app/src/main/res/drawable/community.xml
  app/src/main/res/drawable/community_blue.xml
  app/src/main/res/drawable/menu_selector_community_color.xml
  app/src/main/res/navigation/main_nav.xml
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/com.android.mediproject/KotlinAndroid.kt
  build.gradle.kts
  core/common/build.gradle.kts
  core/common/src/main/java/com/android/mediproject/core/common/bindingadapter/BindingAdapter.kt
  core/common/src/main/java/com/android/mediproject/core/common/constant/MedicationType.kt
  core/common/src/main/res/values/arrays.xml
  core/common/src/main/res/values/strings.xml
  core/ui/build.gradle.kts
  core/ui/src/main/res/layout/medicine_search_list_viewgroup.xml
  core/ui/src/main/res/values/string.xml
  feature/camera/build.gradle.kts
  feature/camera/src/main/java/com/android/mediproject/feature/camera/MedicinesDetectorViewModel.kt
  feature/camera/src/main/res/layout/fragment_detected_image_dialog.xml
  feature/camera/src/main/res/layout/fragment_medicines_detector.xml
  feature/camera/src/main/res/navigation/camera_nav.xml
  feature/comments/build.gradle.kts
  feature/comments/src/main/java/com/android/mediproject/feature/comments/recentcommentlist/RecentCommentListFragment.kt
  feature/community/.gitignore
  feature/community/build.gradle.kts
  feature/community/consumer-rules.pro
  feature/community/proguard-rules.pro
  feature/community/src/androidTest/java/com/android/mediproject/feature/community/ExampleInstrumentedTest.kt
  feature/community/src/main/AndroidManifest.xml
  feature/community/src/main/java/com/android/mediproject/feature/community/CommunityFragment.kt
  feature/community/src/main/java/com/android/mediproject/feature/community/CommunityViewModel.kt
  feature/community/src/main/res/layout/fragment_community.xml
  feature/community/src/main/res/navigation/community_nav.xml
  feature/community/src/main/res/values/strings.xml
  feature/community/src/test/java/com/android/mediproject/feature/community/ExampleUnitTest.kt
  feature/home/build.gradle.kts
  feature/home/src/main/res/navigation/home_nav.xml
  feature/interestedmedicine/build.gradle.kts
  feature/intro/build.gradle.kts
  feature/intro/src/main/res/navigation/intro_nav.xml
  feature/medicine/build.gradle.kts
  feature/mypage/build.gradle.kts
  feature/news/build.gradle.kts
  feature/penalties/src/main/java/com/android/mediproject/feature/penalties/recentpenaltylist/RecentPenaltyListFragment.kt
  feature/search/build.gradle.kts
  feature/search/src/main/java/com/android/mediproject/feature/search/result/manual/ApprovedMedicinesAdapter.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/result/manual/ManualSearchResultFragment.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/result/manual/ManualSearchResultViewModel.kt
  feature/search/src/main/res/layout/fragment_ai_search_result.xml
  feature/search/src/main/res/layout/fragment_manual_search_result.xml
  feature/search/src/main/res/layout/manual_medicine_item.xml
  feature/setting/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 버그, enhancement, newfeature, 박준성, 안드로이드

#55 #54/feature/jsp/lottie dialog
  app/src/main/res/navigation/main_nav.xml
  core/common/build.gradle.kts
  core/common/src/main/java/com/android/mediproject/core/common/bindingadapter/BindingAdapter.kt
  core/common/src/main/java/com/android/mediproject/core/common/dialog/ProgressDialog.kt
  core/common/src/main/java/com/android/mediproject/core/common/dialog/ProgressIndicator.kt
  core/common/src/main/res/drawable/progress_background.xml
  core/common/src/main/res/raw/bluedottedprogress.json
  core/common/src/main/res/values/ids.xml
  core/common/src/main/res/values/strings.xml
  feature/camera/src/main/java/com/android/mediproject/feature/camera/MedicinesDetectorFragment.kt
  feature/camera/src/main/java/com/android/mediproject/feature/camera/imagedialog/DetectedImageFragment.kt
  feature/camera/src/main/res/layout/fragment_medicines_detector.xml
  feature/camera/src/main/res/values/strings.xml
  feature/search/src/main/res/navigation/search_medicines_nav.xml
  gradle/libs.versions.toml
Labels: enhancement, newfeature, 박준성, 안드로이드

#57 #56 fix bindingAdapter관련 기존 xml에서 사용하고 있던 imgUrl과 같은 속성을 img로 통일
  feature/camera/src/main/res/layout/fragment_detected_image_dialog.xml
  feature/camera/src/main/res/layout/item_view_detected_object.xml
  feature/search/src/main/res/layout/manual_medicine_item.xml
Labels: 버그, 안드로이드

#60 #40 feat 커스텀 바 뒤로가기 눌렀을 때 로직 추가
  app/src/main/res/navigation/main_nav.xml
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Bar.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroFragment.kt
  feature/search/src/main/res/layout/fragment_manual_search_result.xml
  feature/search/src/main/res/layout/fragment_search_medicines.xml
Labels: 설계, 안태규, 안드로이드

#70 #69/feature/tgyuu/app icon
  app/src/main/AndroidManifest.xml
  app/src/main/ic_medilenz-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_medilenz.xml
  app/src/main/res/mipmap-anydpi-v26/ic_medilenz_round.xml
  app/src/main/res/mipmap-hdpi/ic_medilenz.png
  app/src/main/res/mipmap-hdpi/ic_medilenz_background.png
  app/src/main/res/mipmap-hdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-hdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-mdpi/ic_medilenz.png
  app/src/main/res/mipmap-mdpi/ic_medilenz_background.png
  app/src/main/res/mipmap-mdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-mdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-xhdpi/ic_medilenz.png
  app/src/main/res/mipmap-xhdpi/ic_medilenz_background.png
  app/src/main/res/mipmap-xhdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-xxhdpi/ic_medilenz.png
  app/src/main/res/mipmap-xxhdpi/ic_medilenz_background.png
  app/src/main/res/mipmap-xxhdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_medilenz.png
  app/src/main/res/mipmap-xxxhdpi/ic_medilenz_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_medilenz_round.png
  app/src/main/res/values/strings.xml
Labels: 설계, enhancement, 안태규, 안드로이드, 베이스

#71 #64/refactor/tgyuu/splash
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_medilenz-playstore.png
  app/src/main/java/com/android/mediproject/MainActivity.kt
  app/src/main/res/mipmap-hdpi/ic_medilenz.png
  app/src/main/res/mipmap-hdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-hdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-mdpi/ic_medilenz.png
  app/src/main/res/mipmap-mdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-mdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-xhdpi/ic_medilenz.png
  app/src/main/res/mipmap-xhdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-xxhdpi/ic_medilenz.png
  app/src/main/res/mipmap-xxhdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_medilenz_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_medilenz.png
  app/src/main/res/mipmap-xxxhdpi/ic_medilenz_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_medilenz_round.png
  app/src/main/res/navigation/main_nav.xml
  app/src/main/res/values/arrays.xml
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseActivity.kt
  core/ui/src/main/res/drawable/medlens_text_logo.png
  core/ui/src/main/res/values/styles.xml
  feature/splash/.gitignore
  feature/splash/build.gradle.kts
  feature/splash/consumer-rules.pro
  feature/splash/proguard-rules.pro
  feature/splash/src/androidTest/java/com/android/mediproject/feature/splash/ExampleInstrumentedTest.kt
  feature/splash/src/main/AndroidManifest.xml
  feature/splash/src/main/java/com/android/mediproject/feature/splash/SplashFragment.kt
  feature/splash/src/main/java/com/android/mediproject/feature/splash/SplashViewModel.kt
  feature/splash/src/main/res/layout/fragment_splash.xml
  feature/splash/src/main/res/values/strings.xml
  feature/splash/src/test/java/com/android/mediproject/feature/splash/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 설계, enhancement, 안태규, 안드로이드, project

#74 DB 연관성 추가 및 변수명 일부 수정
  .DS_Store
  .idea/.gitignore
  .idea/misc.xml
  .vscode/launch.json
  server/.DS_Store
  server/src/.DS_Store
  server/src/models/comment.js
  server/src/models/favoriteMedicine.js
  server/src/models/like.js
  server/src/models/medicine.js
  server/src/models/recentBrowsed.js
  server/src/models/user.js
  server/src/service/userService.js
Labels: 서재완, 백엔드, 🔨refactor🔨

#79 #78/fix/juno/sign in
  server/app.js
  server/package-lock.json
  server/package.json
  server/src/config/responseMsg.js
  server/src/routes/home/index.js
  server/src/routes/user/userRouter.js
  server/src/service/userService.js
  server/swagger/swagger.js
Labels: enhancement, 문준호, 백엔드

#81 #80/fix/juno/sign up
  server/src/config/responseMsg.js
  server/src/routes/user/userRouter.js
  server/src/service/userService.js
Labels: enhancement, 문준호, 백엔드

#85 #76/feature/jsp/signinup
  app/src/main/AndroidManifest.xml
  build.gradle.kts
  core/common/build.gradle.kts
  core/common/src/main/java/com/android/mediproject/core/common/dialog/ProgressDialog.kt
  core/common/src/main/java/com/android/mediproject/core/common/dialog/ProgressIndicator.kt
  core/common/src/main/java/com/android/mediproject/core/common/network/MediDispatchers.kt
  core/common/src/main/java/com/android/mediproject/core/common/network/di/DispatchersModule.kt
  core/common/src/main/java/com/android/mediproject/core/common/uiutil/Keyboard.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/AesCoder.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/DelayEditTextWatcher.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/RegexChecker.kt
  core/common/src/main/res/drawable/progress_background.xml
  core/data/src/main/java/com/android/mediproject/core/data/remote/di/RepositoryModule.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
  core/datastore/build.gradle.kts
  core/datastore/src/androidTest/java/com/android/mediproject/core/datastore/ExampleInstrumentedTest.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/DataStoreModule.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSource.kt
  core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenSerializer.kt
  core/datastore/src/main/proto/connection_token.proto
  core/domain/src/main/java/com/android/mediproject/core/domain/sign/SignUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/parameters/SignInParameter.kt
  core/model/src/main/java/com/android/mediproject/core/model/parameters/SignUpParameter.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/base/BaseAwsResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/sign/SignInResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/sign/SignUpResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/token/AccessTokenResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/token/ConnectionTokenDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/remote/token/TokenState.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/parameter/SignInRequestParameter.kt
  core/network/src/main/java/com/android/mediproject/core/network/parameter/SignUpRequestParameter.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/MediSearchbar.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Subtitle.kt
  core/ui/src/main/res/values/attrs.xml
  feature/intro/build.gradle.kts
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/intro/src/main/res/layout/fragment_login.xml
  feature/intro/src/main/res/layout/fragment_sign_up.xml
  feature/intro/src/main/res/values/strings.xml
  feature/search/src/main/java/com/android/mediproject/feature/search/SearchMedicinesFragment.kt
  feature/search/src/main/res/layout/fragment_search_medicines.xml
  gradle/libs.versions.toml
Labels: enhancement, newfeature, 박준성, 안드로이드, fix

#87 #86/feature/tgyuu/my page guest mode
  feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/intro/src/main/res/navigation/intro_nav.xml
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/res/drawable/guest_user_image.xml
  feature/mypage/src/main/res/drawable/login_button.xml
  feature/mypage/src/main/res/drawable/signup_button.xml
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement, 안태규, 안드로이드, 디자인, 🔨refactor🔨

#89 #59/feature/tgyuu/my page fragment interested medicine my comment list
  core/common/src/main/java/com/android/mediproject/core/common/mapper/MedicineInfoMapper.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/medicineapproval/MedicineApprovalRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/remote/medicineapproval/MedicineApprovalRepositoryImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineApprovalListUseCase.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineDetailsUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/InterestedMedicine/MedicineInterestedDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/medicineapproval/ApprovedMedicineItemDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/medicineapproval/MedicineApprovalListResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/medicinedetailinfo/MedicineDetailInfoResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/medicine/medicinedetailinfo/MedicineDetatilInfoDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/user/UserDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/user/local/UserDto.kt
  core/model/src/main/java/com/android/mediproject/core/model/user/remote/UserResponse.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/medicineapproval/MedicineApprovalDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/medicineapproval/MedicineApprovalDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/medicineapproval/MedicineApprovalListDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/DataGoKrNetwork.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseFragment.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/HeaderForElementsView.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterestedMedicineFragment.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/InterstedMedicineViewModel.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/moreinterestedmedicine/MoreInterestedMedicineFragment.kt
  feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/moreinterestedmedicine/MoreInterestedMeidicneAdapter.kt
  feature/interestedmedicine/src/main/res/layout/fragment_interested_medicine.xml
  feature/interestedmedicine/src/main/res/layout/item_interested_medicine.xml
  feature/interestedmedicine/src/main/res/values/strings.xml
  feature/intro/src/main/res/layout/fragment_login.xml
  feature/medicine/src/main/java/com/android/mediproject/feature/medicine/basicinfo/host/MedicineBasicInfoViewModel.kt
  feature/medicine/src/main/java/com/android/mediproject/feature/medicine/main/MedicineInfoViewModel.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageMyCommentAdapter.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageMyCommentDecoraion.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/res/drawable/rectangle_10_main.xml
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/layout/item_mypage_mycomment.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/search/src/main/java/com/android/mediproject/feature/search/result/manual/ApprovedMedicinesAdapter.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/result/manual/ManualSearchResultFragment.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/result/manual/ManualSearchResultViewModel.kt
  feature/search/src/main/res/layout/manual_medicine_item.xml
Labels: enhancement, 안태규, 안드로이드, 디자인, 🔨refactor🔨

#90 #44 행정처분 리스트에서 아이템 가져오는 로직 구현 성공 -> 아이템 보여주기 화면 제작 완료
  .idea/misc.xml
  build.gradle.kts
  core/model/src/main/java/com/android/mediproject/core/model/remote/adminaction/AdminActionListItemDto.kt
  feature/news/build.gradle.kts
  feature/news/src/main/java/com/android/mediproject/feature/news/NewsFragment.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/NewsScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/AdminActionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/AdminActionViewModel.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/DetailAdminActionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsuspension/DetailRecallSuspensionViewModel.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsuspension/RecallSuspensionScreen.kt
Labels: enhancement, newfeature, 박준성, 안드로이드, fix

#95 #94/feature/tgyuu/my page more
  core/ui/src/main/res/values/color.xml
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetViewModel.kt
  feature/mypage/src/main/res/drawable/rectangle_20_main.xml
  feature/mypage/src/main/res/drawable/rectangle_20_white.xml
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/mypage/src/main/res/layout/fragment_my_page_more_bottom_sheet.xml
  feature/mypage/src/main/res/values/strings.xml
Labels: 설계, enhancement, 안태규, 안드로이드, 디자인, 🔨refactor🔨
