Repository pknu-wap/2023_1_WAP_APP_TEAM_MEDI, pull requests merged in 2023-08, with the labels that each got.

#199 #195/refactor/tgyuu/intro unit test
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/com.android.mediproject/KotlinAndroid.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineApprovalListUseCase.kt
  core/domain/src/test/java/com/android/mediproject/core/domain/ExampleUnitTest.kt
  core/test/.gitignore
  core/test/build.gradle.kts
  core/test/consumer-rules.pro
  core/test/proguard-rules.pro
  core/test/src/androidTest/java/com/android/mediproject/core/HiltTestRunner.kt
  core/test/src/androidTest/java/com/android/mediproject/core/test/ExampleInstrumentedTest.kt
  core/test/src/main/AndroidManifest.xml
  core/test/src/main/java/com/MainCoroutineRule.kt
  core/test/src/main/java/com/android/mediproject/core/test/repositories/FakeSignRepository.kt
  core/test/src/main/java/com/android/mediproject/core/test/repositories/FakeUserRepository.kt
  core/test/src/test/java/com/android/mediproject/core/test/ExampleUnitTest.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreViewModel.kt
  feature/intro/build.gradle.kts
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/intro/src/test/java/com/android/mediproject/feature/intro/ExampleUnitTest.kt
  feature/intro/src/test/java/com/android/mediproject/feature/intro/LoginViewModelTest.kt
  feature/intro/src/test/java/com/android/mediproject/feature/intro/SignUpViewModelTest.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
  feature/mypage/src/test/java/com/android/mediproject/feature/mypage/MyPageViewModelTest.kt
  gradle/libs.versions.toml
  local - 복사본.properties
  settings.gradle.kts
Labels: 안태규, 안드로이드, 🔨refactor🔨, ⚒️⚒️ 리뷰 완료 수정 필요합니다. ⚒️⚒️

#201 #200/refactor/tgyuu/my page more dialog view model refactoring
  app/src/main/java/com/android/mediproject/MainViewModel.kt
  core/data/src/main/java/com/android/mediproject/core/data/user/UserRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/user/UserRepositoryImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/EditUserAccountUseCase.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetAccountStateUseCase.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetUserUseCase.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/SignUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/requestparameters/ChangePasswordParameter.kt
  core/model/src/main/java/com/android/mediproject/core/model/requestparameters/ChangePasswordRequestParameter.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/user/UserDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/user/UserDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/ServerNetwork.kt
  core/test/src/main/java/com/android/mediproject/core/test/repositories/FakeUserRepository.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/commentsofamedicine/MedicineCommentsViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
  feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
  feature/intro/src/test/java/com/android/mediproject/feature/intro/LoginViewModelTest.kt
  feature/intro/src/test/java/com/android/mediproject/feature/intro/SignUpViewModelTest.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
  feature/mypage/src/test/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModelTest.kt
Labels: 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#202 #128/feature/tgyuu/my page comments real data from server
  core/data/src/main/java/com/android/mediproject/core/data/comments/CommentsRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/comments/CommentsRepositoryImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/EditCommentUseCase.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetCommentsUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/comments/MyComment.kt
  core/model/src/main/java/com/android/mediproject/core/model/comments/MyCommentsListResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/comments/NewComment.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/comments/CommentsDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/comments/CommentsDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/comments/CommentsListDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/ServerNetwork.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/commentsofamedicine/MedicineCommentsViewModel.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListAdapter.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
  feature/medicine/src/main/java/com/android/mediproject/feature/medicine/main/MedicineInfoViewModel.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageMyCommentAdapter.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/res/layout/item_mypage_mycomment.xml
Labels: 설계, enhancement, 안태규, 안드로이드, 🌟🌟 머지 해주세요 🌟🌟

#206 #204/refactor/tgyuu/my page UI state and lottie
  core/common/src/main/java/com/android/mediproject/core/common/viewmodel/UiState.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSource.kt
  core/ui/src/main/java/com/android/mediproject/core/ui/base/view/HeaderForElementsView.kt
  core/ui/src/main/res/raw/loading.json
  feature/comments/build.gradle.kts
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListAdapter.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
  feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListViewModel.kt
  feature/comments/src/main/res/layout/fragment_my_comments_list.xml
  feature/comments/src/main/res/layout/item_my_comment.xml
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
  feature/medicine/src/main/java/com/android/mediproject/feature/medicine/main/MedicineInfoFragment.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
  feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/res/layout/fragment_my_page.xml
  feature/news/src/main/java/com/android/mediproject/feature/news/penalties/recentpenaltylist/RecentPenaltyListFragment.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/penalties/recentpenaltylist/RecentPenaltyListViewModel.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsuspension/DetailRecallSuspensionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsuspension/DetailRecallSuspensionViewModel.kt
  feature/search/src/main/java/com/android/mediproject/feature/search/result/ai/AiSearchResultFragment.kt
Labels: enhancement, 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#208 #207/feature/tgyuu/favorite medicine UI state wrapping
  core/ui/src/main/res/values/dimens.xml
  feature/favoritemedicine/build.gradle.kts
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineViewModel.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreViewModel.kt
  feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/recyclerview/FavoriteMeidicneMoreAdapter.kt
  feature/favoritemedicine/src/main/res/layout/fragment_favorite_medicine.xml
  feature/favoritemedicine/src/main/res/layout/fragment_favorite_medicine_more.xml
  feature/mypage/src/main/res/layout/fragment_my_page.xml
Labels: enhancement, 안태규, 안드로이드, 🔨refactor🔨, 🌟🌟 머지 해주세요 🌟🌟

#211 #197/feature/jsp/news
  app/src/main/java/com/android/mediproject/MainActivity.kt
  core/common/src/main/java/com/android/mediproject/core/common/util/SystemBarColorAnalyzer.kt
  core/data/src/main/java/com/android/mediproject/core/data/RepositoryModule.kt
  core/data/src/main/java/com/android/mediproject/core/data/adminaction/AdminActionRepositoryImpl.kt
  core/data/src/main/java/com/android/mediproject/core/data/recallsuspension/RecallSaleSuspensionRepository.kt
  core/data/src/main/java/com/android/mediproject/core/data/recallsuspension/RecallSaleSuspensionRepositoryImpl.kt
  core/data/src/main/java/com/android/mediproject/core/data/safetynotification/SafetyNotificationRepositoryImpl.kt
  core/domain/src/main/java/com/android/mediproject/core/domain/GetRecallSaleSuspensionUseCase.kt
  core/model/src/main/java/com/android/mediproject/core/model/news/recall/DetailRecallSaleSuspensionResponse.kt
  core/model/src/main/java/com/android/mediproject/core/model/news/recall/DetailRecallSuspension.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/android/mediproject/core/network/NetworkStatusManager.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/image/GoogleSearchDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/adminaction/AdminActionDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/adminaction/AdminActionDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/adminaction/AdminActionListDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/recallsuspension/RecallSaleSuspensionDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/recallsuspension/RecallSaleSuspensionDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/recallsuspension/RecallSaleSuspensionListDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/safetynotification/SafetyNotificationDataSource.kt
  core/network/src/main/java/com/android/mediproject/core/network/datasource/news/safetynotification/SafetyNotificationDataSourceImpl.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/DataGoKrNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/GoogleSearchNetwork.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/NetworkModule.kt
  core/network/src/main/java/com/android/mediproject/core/network/module/datagokr/DataGoKrNetworkApi.kt
  core/network/src/main/java/com/android/mediproject/core/network/retrofitext/NetworkApiCallAdapterFactory.kt
  core/network/src/main/java/com/android/mediproject/core/network/retrofitext/NetworkApiResult.kt
  core/test/build.gradle.kts
  core/test/src/main/java/com/android/mediproject/core/test/MainCoroutineRule.kt
  core/ui/src/main/res/values/styles.xml
  feature/home/src/main/java/com/android/mediproject/feature/home/HomeFragment.kt
  feature/home/src/main/java/com/android/mediproject/feature/home/HomeViewModel.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/intro/src/test/java/com/android/mediproject/feature/intro/LoginViewModelTest.kt
  feature/intro/src/test/java/com/android/mediproject/feature/intro/SignUpViewModelTest.kt
  feature/mypage/src/test/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModelTest.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/ComposePagingUtil.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/Constants.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/ListStateSaver.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/NavRoutes.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/NewsScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/AdminActionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/AdminActionViewModel.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/DetailAdminActionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsalesuspension/DetailRecallSaleSuspensionViewModel.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsalesuspension/DetailRecallSuspensionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsalesuspension/RecallSuspensionScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/recallsalesuspension/RecallSuspensionViewModel.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/safetynotification/DetailSafetyNotificationScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/safetynotification/SafetyNotificationScreen.kt
  feature/news/src/main/java/com/android/mediproject/feature/news/safetynotification/SafetyNotificationViewModel.kt
Labels: enhancement, 박준성, 안드로이드, fix, 🌟🌟 머지 해주세요 🌟🌟

#209 #203/feature/juno/user profile image
  server/app.js
  server/bin/www.js
  server/package-lock.json
  server/package.json
  server/src/config/multer.js
  server/src/config/staticDirLoc.js
  server/src/controller/user/user.ctrl.js
  server/src/models/user.js
  server/src/routes/user/userRouter.js
  server/src/service/userService.js
Labels: enhancement, 문준호, 서재완, 백엔드, 🔥🔥 코드 리뷰 기다리는 중 🔥🔥

#218 Server main 병합
  .DS_Store
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  .vscode/launch.json
  package-lock.json
  server/.DS_Store
  server/.gitignore
  server/README.md
  server/app.js
  server/bin/www.js
  server/package-lock.json
  server/package.json
  server/remote.txt
  server/src/.DS_Store
  server/src/config/README.md
  server/src/config/jwt.js
  server/src/config/multer.js
  server/src/config/response.js
  server/src/config/responseMsg.js
  server/src/config/sequelize.js
  server/src/config/sequelizeAuto.js
  server/src/config/staticDirLoc.js
  server/src/controller/README.md
  server/src/controller/comment/index.js
  server/src/controller/medicine/favorite/favorite.ctrl.js
  server/src/controller/user/user.ctrl.js
  server/src/models/README.md
  server/src/models/comment.js
  server/src/models/favoriteMedicine.js
  server/src/models/index.js
  server/src/models/like.js
  server/src/models/medicine.js
  server/src/models/user.js
  server/src/routes/README.md
  server/src/routes/home/index.js
  server/src/routes/medicine/comment/index.js
  server/src/routes/medicine/favorite/index.js
  server/src/routes/medicine/index.js
  server/src/routes/user/userRouter.js
  server/src/service/commentService.js
  server/src/service/medicineService.js
  server/src/service/userService.js
  server/swagger/swagger.js
Labels: enhancement, 문준호, 서재완, 백엔드
